### PR TITLE
add simple regression test

### PR DESCRIPTION
**Pull request by jkittner**
I added a simple regression test, that runs the QC with (almost) default) settings on some (once) randomly generated data (no real CWS data from netatmo involved here !).

I took data from our climate station as a baseline and then randomized it and created the expected errors manually:

output

resulting in this QC output
```console
+++++++++++++++++++++++++++++
+ CrowdQC+ input data check +
+++++++++++++++++++++++++++++
Check 1a - Required columns:
     OK
Check 1b - Optional columns:
     OK
Check 2 - Temporal coverage:
     OK
Check 3 - Regularity:
     OK
Check 4 - Geographical extent:
     ! Geographic extent is large (> 100 km x 100 km).
     --> You might want to split your data into smaller regions.
Check 5 - Number of stations:
     OK
++++++++++++++++++++++++++++++
+ CrowdQC+ output statistics +
++++++++++++++++++++++++++++++
Raw data: 297911 values, 408 stations
QC level m1: 292051 values (= 98.03 % of raw data), 404 stations
QC level m2: 271565 values (= 91.16 % of raw data), 400 stations
QC level m3: 258437 values (= 86.75 % of raw data), 329 stations
QC level m4: 258319 values (= 86.71 % of raw data), 316 stations
QC level m5: 228822 values (= 76.81 % of raw data), 289 stations
QC level o1: 268723 values (= 90.20 % of raw data), 289 stations
QC level o2: 145436 values (= 48.82 % of raw data), 207 stations
QC level o3: 97591 values (= 32.76 % of raw data), 129 stations
```

the test simply:
1. loads the example data
2. runs the qc
3. checks the result of the qc against the expected file

If we'd accidentally break somethings, which would not result in an error, but in slightly changed values, we'd notice it this way. I am missing this practice in many scientific packages - so one could be at least somewhat sure, that things that used to work still work the same way.

### CODE REVIEW

**Comment by dafenner** [comment]
Thanks @jkittner , that is a great addition!
I'm wondering if we should put the actual data in a `data` directory instead of `tests` to have it as an example for users to work with and how the data should be formatted. Of course, the data is there, but less findable.
What do you think?

**Comment by jkittner** [comment]
yes, that would be nice! One issue I was not able to solve (so far) is, that `m5`, the spatial buddy check, quickly notices the randomness of the data, so I had to set `m5_alpha` to 0.8 (which is way too high for real world applications) otherwise no station remained in the end.

If you have any idea how to also arbitrarily create a UHI-like spatial pattern, I could add this. Maybe get the center of the ROI, and calculate a random offset depending on the distance from the center. Then maybe also the buddy checks could work...

**Comment by dafenner** [comment]
Well, I think we could still include that as an example data set. It also nicely shows that if the stations are too different from one another in terms of temperature, the QC actually works. ;-)
This link is helpful in explaining the directory structure: https://cran.r-project.org/doc/manuals/R-exts.html#Data-in-packages
So: `data`directory and at best save the file as .rda (or .txt, better not .csv (see link above, if I understand correctly)). Also include a `datalist` file (no extension), which speeds up the package installation apparently. 
How big is the file for two month? If too big, we could go with one month.
Could you reduce the spatial extent a bit to not raise a warning in `cqcp_check_input`?
Later we can also add @examples for the individual functions.

**Comment by jkittner** [comment]
okay, I'll look into the packaging part! and generate a one month example dataset with ~ 500 stations.

I had another go at creating nice data and arbitrarily create an UHI-pattern as well as a vertical temperature gradient.

ts
spatial

So I am wondering whether we could translate my python code to R to have a function `cqcp_generate_data` at a later point?
the current API looks like that:
```python
def generate_cws_data(
        baseline_cycle: pd.Series,
        nr_stations: int,
        *,
        resolution: str = '1H',
        delta_ta: float = 4,
        perc_monotonic_stations: float = 0.01,
        perc_duplicated_positions: float = 0.05,
        perc_isolated_stations: float = 0.04,
        min_temp: float = 10,
        max_temp: float = 30,
        geometry: bool = False,

) -> pd.DataFrame:
    ...
```
where you can provide some baseline (data from a PWS - we could also add some data from our stataion as a default) and the decide how many stations you want, in what resolution how strong the UHI effect should be, what the shares of the different errors should be and finally the temperature range the cycle should be scaled to.

**Comment by dafenner** [comment]
I like the new data set, looks interesting! 
Don't spend too much time on that. It's a great addition and will be very helpful in the future (code testing, new users). It's OK to have it produced outside of the package.
A new function is nice, but I actually think the applicability is limited.

**Comment by jkittner** [comment]
okay 👍 - then I'll just adapt the folder structure and file-format and update the files.

**Comment by jkittner** [comment]
okay, this is done and the data is hopefully packaged correctly. Build and installation succeeds and I'm able to load the data.

Currently the test coverage looks like that:
```console
 CrowdQCplus Coverage: 50.10%
R/cqcp_helper.R: 34.19%
R/cqcp_filter.R: 68.20%
```

So ideally we would bring this up to 100 % in the future, but for now this is a nice thing to have to be at least sure nothing major changed/broke.

**Comment by dafenner** [comment]
Very nice work, thanks @jkittner !
I will merge and add some examples to the documentation, then we can create a new release.
Thanks again!

**Review by dafenner — APPROVED** [review]
approved, looks great!

**Pull request merged**
